name: FCS compile check
on:
  push:
    branches: [ main ]
  workflow_dispatch:
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: xu-cheng/latex-action@v3
        with:
          root_file: FCS LaTeX Template(1)/template.tex
          latexmk_use_xelatex: false
          args: -pdf -file-line-error -interaction=nonstopmode
